4.1 사라진 SQLException
=
## 4.1.1 초난감 예외처리
### 예외 블랙홀
#### 예외를 잡고 아무것도 하지 않음
```java
try {
        ...
}
catch (SQLException e) {
}
```

#### 콘솔/로그에 예외 메시지만 남김
```java
} catch (SQLException e) {
    System.out.println(e);
}
```

```java
} catch (SQLException e) {
    e.printStackTrace();
}
```
- 예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 그리고 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위함한 일임.
- 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문에 원치 않는 예외가 발생하는 것보다도 훨씬 더 나쁜 일이다.
- 이러한 예외 처리로 인하여 &rarr; 기능이 비정상적으로 동작/메모리나 리소스 소진/예상치 못한 다른 문제 발생 등
- 즉 시스템 오류/오작동을 초래하는데 알아차렸을 때에 오류의 원인이 무엇인지 찾아내기 매우 힘들게 됨
- 따라서 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 통보돼야 함.

## 4.1.2 예외의 종류와 특징
예외처리에 관해서 자바 개발자들 사이에서도 많은 논쟁이 있었음. 그 중 하나가 체크 예외.
- 체크 예외: 명시적인 처리가 필요한 예외를 사용하고 다루는 방법

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있음 &rarr; 1) Error 2) Exception과 체크 예외 3) RuntimeException과 언체크/런타임 예외

1) Error
   - 시스템에 비정상적인 상황이 발생했을 경우에 사용됨
   - 자바 VM에서 발생시키는 것이므로 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 됨
2) Exception과 체크 예외
    - 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용됨
    - Exception 클래스는 다시 체크 예외(Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것)와 언체크 예외(RuntimeException을 상속한 클래스들)로 나뉨
    - 일반적으로 예외라고 하면 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 됨
    - 체크 예외가 발생할 수 있는 메소드를 사용하는 경우 반드시 예외를 처리하는 코드를 함께 작성해야 함 &rarr; 그렇지 않으면 컴파일 에러 발생
    - IOException이나 SQLException이 체크 예외로 만들어져 있음
3) RuntimeException과 언체크/런타임 예외
    - 언체크 예외/런타임 예외라고 불림
    - 예상 못한 예외상황에서 발생하는 것이 아니므로, catch 문으로 잡거나 throws로 선언하지 않아도 됨
    - NullPointerException이나 IllegalArgumentException 등이 있음

## 4.1.3 예외처리 방법
### 예외 복구
- 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것
- 재시도를 통해 예외 복구를 시도. 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 함
```java
int maxretry = MAX_RETRY;
while (maxretry -- > 0) {
    try {
        ...         // 예외가 발생할 가능성이 있는 시도
        return;     // 작업 성공
    }
    catch (SomeException e) {
        // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
        // 리소스 반납. 정리 작업
    }
}
throw new RetryFailedException();   // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

### 예외처리 회피
- 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것
- 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 다음 코드와 같이 던져줘야 함
```java
public void add() throws SQLException {
    // JDBC API
}
```

```java
public void add() throws SQLException {
    try {
        // JDBC API
    }
    catch (SQLException e) {
        // 로그 출력
        throw e;
    }
}
```
- 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 것은 무책임한 책임회피일 수 있음
- 그러므로 예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 함
- 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야 함

### 예외 전환
- 예외를 적절한 예외로 전환해서 메소드 밖으로 던지는 것
- 2가지 목적
  - 1) 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위함
    - 예)
    - 아이디 중복 &rarr; DB 에러 발생 &rarr; SQLException 발생
    - 이때 DuplicateUserIdException 같은 예외로 바꿔서 던져주는 게 좋음
        ```java
        // 예외 전환 기능을 가진 DAO 메소드
        public void add(User user) throws DuplicateUserIdException, SQLException {
            try {
                // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
                // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
            }
            catch (SQLException e) {
                // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
                if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
                    throw DuplicateUserIdException();
                else
                    throw e; // 그 외의 경우는 SQLException 그대로
            }
        }
        ```
    - 보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외로 만드는 것이 좋음 &rarr; getCause() 메소드를 이용해서 처음 발생한 예외가 무엇인지 확인 가능
        ```java
        catch (SQLException e) {
            ...
            throw DuplicateUserIdException(e);
        }
        ```
      
        ```java
        catch (SQLException e) {
            ...
            throw DuplicateUserIdException().initCause(e);
        }
      ```
  - 2) 예외를 처리하기 쉽고 단순하게 만들기 위해 포장하는 것
    - 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에, 중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던짐
    - 대표적으로 EJBException
    ```java
    try {
	    OrderHome orderHome = EJBHomeFactiory.getInstance().getOrderHome();
	    Order order = orderHome.findByPrimaryKey(Integer id);
    } catch(NamingException ne) {
        throw new EJBException(ne);
    } catch(FinderException ne) {
        throw new EJBException(ne);
    } catch(RemoteException ne) {
        throw new EJBException(ne);
    }
    ```
    - 이렇게 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백함
    - 런타임 예외이기 때문에 EJB 컴포넌트를 사용하는 다른 EJB나 클라이언트에서 일일이 예외를 잡거나 다시 던지는 수고를 할 필요가 없음 &rarr; 잡아도 복구할 만한 방법이 없기 때문

## 4.1.4 예외처리 전략
### 런타임 예외의 보편화
- 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단
- 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우, 빨리 해당 요청의 작업을 취소하고 서버 관리자나 개발자엑 통보

&rarr; 체크 예외의 활용도와 가치는 점점 떨어지고 있음

&rarr; 복구 불가능한 상황이라면 RuntimeException으로 던지거나 API 차원에서 런타임 예외를 던지도록 만드는 것

### add() 메소드의 예외처리
- SQLException은 대부분 복구 불가능한 예외이므로, 런타임 예외로 포장해 던져버려서 그 밖의 메소드들이 신경 스지 않게 해주는 편이 낫다.
```java
public void add() throws DuplicateUserIdException {
    try {
        // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
        // 그런 기능이 있는 다른 SQLException을 던지는 메소드를 호출하는 코드
    }
    catch (SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw new DuplicateUserIdException(e);  // 예외 전환
        else
            throw new RuntimeException(e);  // 예외 포장
    }
}
```
- 이 add() 메소드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서, 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicatedUserIdException을 이용할 수 있음
- 이렇게 런타임 예외를 일반화해서 사용하는 방법은 장점이 많다.
- 하지만 컴파일러가 예외처리를 강제하지 않아 예외상황을 충분히 고려하지 않을 수도 있기 때문에, 런타임 예외로 만들었기 때문에 사용에 더 주의를 기울일 필요도 있다.
- 런타임 예외를 사용하는 경우에는 API 문서나 레퍼런스 문서를 통해 메소드를 사용할 때 발생하는 예외의 종류와 원인, 활용 방법을 설명해두자.

### 애플리케이션 예외
- 시스템 또는 외부의 예외상황이 원인이 아니라, 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외
- 정상적적인 결과가 나왔을 경우와 아닐 경우에 각각 다른 종류의 리턴 값을 돌려주기
  - 이때 일관된 예외상황에서의 결과 값에 대한 정책을 완벽하게 갖추고, 사전에 상수로 정의해둔 표준 코드를 사용하지 않으면 정확한 의사소통 불가능
  - 결과 값을 확인하는 if 문이 자주 등장하는 문제가 있음
- 비정상적인 결과 때에만 비즈니스적인 의미를 띤 예외를 던지기
  - 정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드를 try 블록 안에 깔끔하게 정리해두고 예외상황에 대한 처리는 catch 블록에 모아둘 수 있기 때문에 이해하기 편함
  - 번거로운 if 문을 남발하지 않아도 됨
- 이때 사용하는 예외는 의도적으로 체크 예외로 만든다. &rarr; 자주 발생 가능한 예외상황에 대한 로직을 개발자가 잊지 않고 구현하도록 강제함
```java
// 애플리케이션 예외를 사용한 코드
try {
    BigDecimal balance = account.withdraw(amount);
    ...
    // 정상적인 처리 결과를 출력하도록 진행
}
catch (InsufficientBalanceException e) {    // 체크 예외
    // InsufficientBalanceException에 담긴 인출 가능한 잔고금액 정보를 가져옴
    BigDecimal availFunds = e.getAvailFunds();
    ...
    // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
}
```

## 4.1.5 SQLException은 어떻게 됐나?
- 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다. 프로그램의 오류 또는 개발자의 부주의 때문에 발생하는 경우이거나, 통제할 수 없는 외부상황 때문에 발생하는 것이다.
- 예) SQL 문법 틀림/제약조건 위반/DB 서버 다운/네트워크 불안정/DB 커텍션 풀을 가져올 수 없는 경우
- 스프링의 JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다.
- 따라서 DAO에서 꼭 필요한 경우에만 런타임 예외를 잡아서 처리하면 되고, 그 외에는 무시하면 된다.
- JdbcTemplate의 메소드 선언을 보면 모두 throws DataAccessException이라고 되어 있음 &rarr; throws로 선언되어 있긴 하지만 런타임 예외이므로 메소드에서 잡거나 다시 던질 의무는 없음
- 그 밖에도 스프링의 API 메소드에 정의되어 있는 대부분의 예외는 런타임 얘외다. &rarr; 발생 가능한 예외가 있더라도 이를 처리하도록 강제하지 않는다.