- jdbcTemplate을 사용할 시 throws SQLException가 사라졌다.
- SQLException은 JDBC API 메소드들이 던져주는 것이므로 당연히 있어야 한다. 어째서 내부적으로 JDBC API를 쓰는 jdbcTemplate가 SQLException을 바깥으로 던지지 않는가?
```java
public void deleteAll() throws SQLException {
  this.jdbcContext.executeSql("delete from users");
}
```

```java
public void deleteAll() {
  this.jdbcTemplate.update("delete from users");
}
```

## 4.1.1. 초난감 예외 처리
### 예외 블랙홀
- 예외를 잡고 아무 처리도 하지 않는다
- 예외가 발생하면 그것을 catch 블록을 써서 잡아내고 예외 처리를 해주어야한다. 어떤 기능이 비정상적인 동작을 하거나 메모리/리소스 소진 등의 예상치 못한 문제를 일으킬 수도 있기 때문이다
```java
try {
  ...
} catch (Exception e) {}
```

- 예외는 반드시 적절하게 복구되든지 작업을 중단시키고 운영자 또는 개발자에게 통보돼야 한다
- 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다. 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버려라

### 무의미하고 무책임한 throws
- throws Exception처럼 예외를 던지기만 하고 처리하지 않는다
-  적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다
```java
public void method1() throws Exception {
  method2();
  ...
}

public void method2() throws Exception {
  method3();
  ...
}

public void method3() throws Exception ...
```

## 4.1.2 예외의 종류와 특징
- 자바에서 throw를 통해 발생시킬  수 있는 예외
#### 1. Error
- 시스템에 비정상적인 상황이 발생했을 때
- JVM에서 발생
- 시스템 레벨에서 발생하기 때문에 애플리케이션에서 신경쓰지 않아도 된다

#### 2. Exception과 체크 예외
- 애플리케이션 코드의 작업 중 예외 상황이 발생했을 때
a. 체크 예외
- 일반적인 예외
- Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 클래스
- `throw ~` 를 반드시 작성해야 함
 - 예외 처리를 강제함 -> catch문으로 잡든지, 아니면 다시 trhows를 정의해서 메소드 밖으로 던져야 한다
- 예외 처리를 하지 않으면 throws를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져진다
- 예: IOException, SQLException 등
b. 언체크 예외
- 시스템 장애나 프로그램상의 오류
- RuntimeException 클래스를 상속한 클래스
- 예외 처리를 강제하지 않은 것 뿐이지, 예외처리를 해도 된다

![image](https://github.com/user-attachments/assets/39a640fa-0ebf-41a1-a827-296a5a7f492a)


#### 3. RuntimeException과 언체크/런타임 예외
- 프로그램의 오류가 있을 때 발생하도록 의도한 것이다
- 예상하지 못했던 예외상황에서 발생하는 게 아니기 때문에 굳이 catch나 throws를 사용하지 않아도 된다
- 예: NullPointerException, IllegalArgumentException

## 4.1.3 예외처리 방법
#### 1. 예외 복구
- 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려 놓는 것
- 에러 메시지를 사용자에게 보여주고 다른 대안을 제안해서 예외상황을 해결할 수 있다
- 예: 서버 불안정 -> 예외 발생 -> 다시 접속 유도

#### 2. 예외처리 회피
- 자신이 예외처리를 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것
- throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것
- 예: JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트
  ResultSet이나 PreparedStatement 등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메소드는 모두 throws SQLException이 붙어있다. SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다
- 예외를 회피하는 것은 자신을 사용하는 쪽에서 예외를 다루는 게 최선이라는 확신이 있어야 한다

#### 3. 예외 전환
- 예외를 복구해서 정상적인 상태로 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것
- 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다
- 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서
	- API가 발생하는 기술적인 로우 레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것
- 예외를 처리하기 쉽고 단순하게 만들기 위해 포장하기 위해서
	- 체크 예외 -> 언체크 예외(런타임 예외)로 바꾸는 경우에 사용
	- 복구가 불가능한 예외라면 런타임 예외로 포장해서 던지게 한다
	- 다른 계층이 메소드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 한다

## 4.1.4 예외처리 전략
- 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다
- 대응이 불가능한 체크 예외라면 빨리 런타임 예외로 전환해서 던지는 게 낫다
```java
public class DuplicateUserIdException extends RuntimeException{
    public DuplicateUserIdException(Throwable cause) {
        super(cause);
    }
}

public void add() throws DuplicateUserIdException {
  try {
    // 
  }
  catch (SQLException e) {
    if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw new DuplicateUserIdException(e); // 예외 전환
    else
      throw new RuntimeException(e); // 예외 포장
  }
}
```

- 애플리케이션 예외: 애플리케이션 자체의 로직에 의해 의도적으로 발생함
1. 정상적인 처리를 했을 경우와 의도적으로 예외를 발생시키고자 하는 경우에 각각 다른 종류의 리턴 값을 돌려준다
    - 예외 상황에 대한 리턴 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다
    - 결과 값을 확인하는 조건문이 자주 등장한다
2. 비즈니스적인 의미를 띤 예외를 던진다
	- 의도적으로 체크 예외로 만들어 개발자가 잊지 않고 구현하도록 강제한다

## ✨4.1.5 SQLException은 어떻게 됐나?
- 대부분의 SQLException은 복구가 불가능하다. DAO 밖에서 SQLException을 다룰 수 있는 가능성은 거의 없다
- 예외처리 전략을 적용하고 가능한 빨리 언체크/런타임 예외로 전환해야 한다

- 스프링의 JdbcTemplate이 그 예시다
- JdbcTemplate 템플릿과 콜백 안에서 발생하는 런타임 예외는 SQLException -> DataAccessException으로 포장해 던져준다
- 따라서 런타임 예외인 DataAccessException을 잡아서 처리하면 되고 그 외의 경우에는 무시해도 된다
- 장점
	- 복구 불가능한 예외인 SQLException을 애플리케이션 레벨에서 신경쓰지 않아도 된다
	- DataAccessException은 SQLException에 담긴 힘든 상세한 예외정보를 의미있고 일관성 있는 예외로 전환해서 추상화 한다

- JdbcTemplate의 update(), queryForInt(), query() 메소드 선언을 잘 살펴보면 모두 throws DataAccessException이라고 되어 있음을 발견할 수 있다
- 그 밖에도 스프링의 API 메소드에 정의되어 있는 대부분의 예외는 런타임 예외다. 따라서 발생 가능한 예외가 있다고 하더라도 예외 처리를 강제하지 않는다