4.1 사라진 SQLEXCEPTION
=
- jdbcTemplate을 적용하면서 SQLException이 없어짐

```java
// 변경 전 context를 정의해서 사용할 때
public void deleteAll() throws SQLException {
    this.jdbcContext.executeSql("delete from users");
}
```

```java
// 변경 후 template 사용할 때
public void deleteAll() {
    this.jdbcTemplate.update("delete from users");
}
```

## 4.1.1 초난감 예외처리
### 예외 블랙홀
- 예외를 잡고 아무 처리도 하지 않는 코드

```java
public void practice() {
    // 아무 처리도 하지 않는 경우
    try {
        //...
    } catch(Exepction1 e) {}
}
```
- 예외가 발생했는데 무시하고 진행하기 때문에 문제가 됨
- 문제가 발생한 원인을 찾기 힘들어짐

```java
public void practice() {
    // 예외상황을 화면에 출력만 하는 경우 1
    try {
        //...
    } catch(Exepction2 e) {
        System.out.println(e);
    }

    // 예외상황을 화면에 출력만 하는 경우 2
    try {
        //...
    } catch(Exepction3 e) {
        e.printStackTrace();
    }
}
```
- 다른 로그나 메시지에 묻혀서 못 볼 수 있음
- 예외를 처리한 게 아님



### 예외를 처리할 때 반드시 지켜야 할 핵심 원칙
- 모든 예외는 **적절하게 복구**되든지 아니면 **작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보**되어야 함

### SQLException
- SQL 문법 에러, 데이터 액세스 로직에 심각한 버그, 서버 중단, 네트워크 중단 등 심각한 상황 때문에 발생
- 이를 무시하고 그대로 진행하는 것은 큰 문제
- 차라리 다음과 같이 프로그램을 중단시키는 게 낫다

```java
public void practice() {
    try {
        
    } catch (SQLException e) {
        System.exit(1);
    }
}
```
- 예외를 잡아서 조치를 취할 방법이 없는 경우 차라리 예외를 잡지 말고 throws SQLException을 통해 자신을 호출한 코드에 예외처리 책임을 전가하는 게 낫다

### 무의미하고 무책임한 throws
- API나 라이브러리가 던지는 예외를 처리하기 귀찮아서 그냥 Exception을 기계적으로 붙이는 경우

```java
public void method1() throws Exception {
    method2();
}
public void method2() throws Exception {
    method3();
}
public void method3() throws Exception {
    // ... 
}
```
- throws Exception 은 예외에 대한 의미 있는 정보를 포함하지 않음
- 예를 들면, 해당 예외가 실행 중 발생할 수 있는 예외인지, 아니면 습관적으로 붙인 것인지 알 수 없음
- 해당 메소드를 사용하는 다른 메소드에서도 예외 처리할 수 있는 기회 없이 그냥 throws Exception 붙이는 방법밖에 없음

## 4.1.2 예외의 종류와 특징
- 자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 3가지 
### Error
- `java.lang.Error` 클래스의 서브클래스들
- 시스템에 비정상적인 상항이 발생했을 경우에 사용
- 따라서, 주로 VM에서 발생시키는 것이며 애플리케이션 코드에서 잡으려고 하면 안됨 (대응 방법이 없기 때문)
- ex) `OutOfMemoryError`, `ThreadDeath`

### Exception과 체크 예외
- `java.lang.Exception` 클래스와 그 서브클래스로 정의됨
- 에러와 달리 애플리케이션 코드의 작업 중에 발생하는 예외상황
- Exception 클래스는 체크 예외와 언체크 예외로 구분

#### 체크 예외
- Exception의 서브클래스이면서 RuntimeException 클래스를 상속하지 않음 (언체크는 RuntimeException 클래스를 상속)
  
![image](https://github.com/user-attachments/assets/62bd96a2-9472-43d9-94a7-121f970127b9)
- 일반적으로 예외라고 하면 체크 예외만을 가르킴
- 체크 예외가 발생할 수 있는 메소드 사용 시 반드시 예외 처리 코드를 작성해야 함 (`try/catch` or `throws`)

### RuntimeException과 언체크/런타임 예외
- java.lang.RuntimeException 클래스를 상속한 예외
- 명시적인 예외처리를 강제하지 않음
- 프로그램의 오류가 있을 때 발생하도록 의도됨
- ex1) `NullPointerException` : 오브젝트를 할당하지 않은 참조 변수 사용 시 발생
- ex2) `IllegalArgumentException : 허용되지 않는 값을 사용해 메소드 호출
- 코드에서 미리 조건을 체크하여 피할 수 있지만 놓쳤을 경우에 발생하도록 만들어짐
- 즉, 예상치 못한 예외상황에서 만들어진 것이 아니기 떄문에 처리 강제 x

#### [참고]
- 설계의도가 현실과 잘 맞지 않는다는 비난
- 체크 예외의 강제 때문에 예외 블랙홀, 무책임한 throws 등의 코드가 남용됨
- 최근 새로 등장하는 자바 표준 스팩의 API는 예상 가능한 예외를 체크 예외로 만들지 않는 경향

## 4.1.3 예외처리 방법

### 1. 예외 복구
- 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것
- 다른 작업 흐름으로 유도
- 애플리케이션에서 정상적으로 설계된 흐름을 따라 진행되어야 함
- 주로 체크 예외에서 사용 &rarr; 개발자로 하여금 예외 처리 시도를 유도

#### EX) IOException
- 파일 읽기를 시도했는데 파일이 없는 등의 문제
- 예외 복구 : 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내

#### EX) SQLException
- 네트워크가 불안해서 서버 접속이 어려운 환경의 시스템에서 원격 DB 접속 실패 상황을 가정
- 예외 복구 : 일정 시간 대기했다가 다시 접속을 시도해보는 방법 사용

```java
public void practice() {
    int maxretry = MAX_RETRY;
    while(maxretry-- == 0) {
        try {
            
        } catch (SomeException e) {
            // 로그 출력
            // 정해진 시간동안 대기
        } finally {
            // 리소스 반납, 정리 작업
        }
    }
    throw new RetryFailedException();
}
```

### 2. 예외처리 회피
- 예외처리를 자신을 호출한 쪽으로 던져버리기
- throws 문 사용하거나 try/catch 사용해서 로그처리하고 다시 예외 발생시키기

```java
import java.sql.SQLException;

public void add() throws SQLException {
    // JDBC API
}

public void add2() throws SQLException {
    try{
        // JDBC API
    } catch (SQLException e) {
        // 로그 출력
        throw e;
    }
}
```
- JDBC에서 사용하는 콜백 오브젝트의 메소드들은 SQLException을 직접 처리하지 않고 throws SQLException으로 다 던짐
- 이를 처리하는 것이 콜백 오브젝트의 역할이아니라고 보기 때문에 템플릿 레벨에서 처리하도록 던져줌
- 하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하는 관계가 아니라면 예외 회피는 무책임
- DAO에서 throws SQLException하면?
  - 서비스 계층이나 컨트롤러 계층도 처리 불가, 계속 회피해서 그냥 서버로 전달될 것
- 따라서, **예외 회피의 경우에도 의도가 분명해야** 한다!
  - 다음의 상황이 예외 처리의 방법 중 최선의 방법일 때만 사용
    - 나와 긴밀한 관계에 있는 다른 오브젝트에게 예외를 전달
    - 자신을 사용하는 쪽에게 예외를 전달

### 3. 예외 전환
- 스스로 처리할 수 없어서 예외를 던진다는 점에서 예외 회피와 유사하지만, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있음

### 예외 전환의 두 가지 목적
#### 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우, 의미를 명확하게 해주는 예외로 전환
- ex) 회원가입시 중복 아이디
  - SQLException 발생, 그대로 던지면 DAO는 어떤 상황 때문에 발생한 SQLException인지 파악할 수 없음
  - 중복 아이디는 충분히 예상 가능하고 복구 가능한 예외이므로 DuplicateUserIdException 등의 예외로 바꿔서 던지는 것이 좋음
- 의미가 분명한 예외가 던져지면 서비스 계층 오브젝트는 적절한 복구 작업을 시도할 수 있음
- 보통 원래 발생한 예외를 담아서 중첩 예외로 만들어 정보를 함께 제공하는 것이 좋음


```java
public void add2(User user) throws DuplicationUserIdException, SQLException {
    try {
        Connection c = connectionMaker.makeConnection();

        PreparedStatement ps = c.prepareStatement(
                "insert into users(id, name, password) values(?,?,?)");
        ps.setString(1, user.getId());
        ps.setString(2, user.getName());
        ps.setString(3, user.getPassword());

        ps.executeUpdate();

        ps.close();
        c.close();

    } catch(SQLException e) {
        if (e.getErrorCode() == 1062) throw new DuplicationUserIdException("아이디 중복으로 인한 예외 발생" + user.getId(), e);
        else throw e;
    }
}
```
```java
public class DuplicationUserIdException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    public DuplicationUserIdException(String message) {
        super(message);
    }

    public DuplicationUserIdException(String message, Throwable cause) {
        super(message, cause);
    }
}

```
- 


#### 예외를 처리하기 쉽고 단순하게 만들기 위해 포장
- 새로운 예외를 만들고 중첩 예외를 사용해 원인이 되는 예외를 내부에 담아서 던지는 방식은 같음
- 주로, 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용
- 일반적으로 해결할 수 없는 체크 예외를 게속해서 throws로 던지는 것은 무의미하며, 가능한 빨리 RuntimeException으로 포장해서 해결하는 것이 바람직
  - 추가적으로 로깅이나 관리자 & 사용자들에게 알리는 등의 행위는 필요함!


- ex) EJBException 
  - EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직 상 의미 없는 예외이거나 복구 불가능한 예외
  - 이런 경우는 런타임 예외인 EJBException으로 포장해서 던지는 게 낫다

```java
public void practice() {
    try {
        
        OrderHome orderHome = EJBHomeFactory.getInstance().getOrderHome();
        Order order = orderHome.findByPrimaryKey(id);
        
    } catch (NamingException | SQLException | RemoteException e) {
        throw new EJBException();
    }
}
```
- 어짜피 잡아도 복구 불가능하기 때문에 RuntimeException으로 감싸서 전달
  - 다른 EJB나 클라이언트에서 예외 잡아서 처리하지 않아도 되도록 함
  - 예외 발생 시 EJB가 이를 시스템 예외로 인식해서 트랜잭션 롤백 

## 4.1.4 예외 처리 전략
### 런타임 예외의 보편화
- 체크 예외는 복구 가능한 예외처리를 강제해 개발자의 실수를 방지하는 역할을 하지만 번거로움
- 초기 자바가 독립적 어플리케이션으로 사용되었을 때는 체크 예외를 통해 예외를 처리해서 시스템 실행을 유지해주어야 했음
- 수많은 사용자의 요청이 독립적 작업으로 취급되는 자바 엔터프라이즈 서버 환경에서는 예외 발생 시 해당 작업만 중단하면 됨
- 또한, 예외 발생 시 모든 작업을 중지하고 해당 예외를 복구하는 작업이 불가능 함
- 따라서, 
  - 애플리케이션 차원에서 예외상황을 파악하고 미리 차단하거나
  - 대응 불가능한 예외(프로그램 오류, 외부 환경의 문제 등)라면 해당 요청의 작업을 취소하고 관계자에게 통보하는 것이 바람직
- 즉, 체크 예외에 대한 활용도와 가치가 하락하고 있음
- 따라서, 항상 복구할 수 있는 예외가 아니라면 일단 RuntimeException으로 만들기

### add() 메소드이 예외처리
- SQLException 은 대부분 복구 불가능한 예외이므로 RuntimeException으로 포장해서 넘겨주는 것이 바람직
- DuplicationUserIdException도 런타임 예외이기 때문에 throws 처리는 필수는 아님, 써줌으로써 의미 있는 정보 전달 가능(문서화, 정적 분석 도구 처리 등)
```java
public void add2(User user) throws DuplicationUserIdException {
    try {
        Connection c = connectionMaker.makeConnection();

        PreparedStatement ps = c.prepareStatement(
                "insert into users(id, name, password) values(?,?,?)");
        ps.setString(1, user.getId());
        ps.setString(2, user.getName());
        ps.setString(3, user.getPassword());

        ps.executeUpdate();

        ps.close();
        c.close();

    } catch(SQLException e) {
        if (e.getErrorCode() == 1062) throw new DuplicationUserIdException("아이디 중복으로 인한 예외 발생" + user.getId(), e);
        else throw RuntimeException(e);
    }
}
```
- 단, 예외 처리를 강제하지 않기 때문에 예외상황을 충분히 고려하지 않게 될 수 있음
- API 문서나 레퍼런스 문서 등을 통해, 발생 가능한 예외의 종류와 원인, 활용 방법을 설명

### 애플리케이션 예외
- 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch해서 조취를 취하도록 요구하는 예외
- 정상처리와 비정상처리의 경우에 각각 다른 종류의 리턴 값을 돌려주는 식으로 처리할 때의 문제점
  - 비정상처리 반환값의 표준이 없음(누구는 0, 누구는 -1이나 -999 반환)
  - 리턴 값 확인하는 조건문이 자주 등장 (가독성 하락)
- 비정상 처리의 경우에 비즈니스적인 의미를 띈 예외를 던지도록 함
  - 예외 발생 가능 코드를 try 문에 모아놓고 catch 문으로 예외잡기 해서 코드 간단하게
- 이때, 사용하는 예외는 개발자의 처리를 강제하기 위해 체크 예외로 만든다

```java
import java.math.BigDecimal;

public void bank() {
    try {
        BigDecimal balance = account.withdraw(amount);
    } catch (InsufficientBalanceException e) {  // 체크 예외 처리
        BigDecimal availFunds = e.getAvailFunds(); 
        
        // 잔고 부족 안내 처리
    }
}
```

## 4.1.5 SQLException 은 어떻게 됐나?
- 99%의 SQLException은 코드 레벨에서 복구 불가능
- 스프링의 JdbcTemplate은 템플릿과 콜백 안에서 발생하는 모든 SQLException 을 런타임 예외인 DataAccessException으로 포장해서 던져줌
- 이렇게 함으로써 DAO 레벨에서는 꼭 필요한 예외만(DataAccessException) 처리하고 그 외에는 무시할 수 있도록 해줌
- JdbcTemplate 의 메소드 선언을 보면 throws DataAccessException으로 명시 해줌
  - 단, RuntimeException이므로 강제는 아님




